### ISSUE TITLE
Tests which should be setting LDI properties are setting test properties

### ISSUE THREAD

**Issue by l0b0** [linz/linz-data-importer#129]
See https://github.com/linz/linz-data-importer/pull/128 - it looks like these tests were setting properties on the test class instance itself rather than on the LDI instance. Am I missing something, or should we

**Comment by billgeo** [comment]
I think you're right. Tests are still running fine, so I guess those parts of the set up and tear down weren't so important? Although maybe causing some of those intermittent issues perhaps?
