### ISSUE TITLE
Aerial Imagery Basemap not loading in QGIS

### ISSUE THREAD

**Issue by grantpearse** [linz/linz-data-importer#159]
Hi LINZ team,

We have quite a few users of your very useful QGIS plugin in the team and we have all notice we can't load the aerial basemap into QGIS using the LINZ plugin at the moment.

When the layer with id:aerial layer name: Aerial Imagery Basemap is added QGIS reports a missing dataset 'Layer Unavailable' 
QGIS error: 'Repair Data Source'
Original Source: Original source URI: contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&layers=aerial&styles=default&tileMatrixSet=EPSG:3857&url=https://basemaps.linz.govt.nz/v1/tiles/aerial/WMTSCapabilities.xml?api=myapikeyremoved

Have tried re-installing the plugin and re-adding the basemaps.linz.govt.nz as a domain with API keys.
Could be co-incidence but the timing of this issue was close the changes in layer names and descriptions perhaps the plugin doesn't reference the new tileset / URL yet?

![image](https://user-images.githubusercontent.com/24468153/181147406-2df40e73-7546-4cda-8bfc-ed2c2b56d32f.png)

Adding the service manually in QGIS works fine using this address: https://basemaps.linz.govt.nz/v1/tiles/aerial/NZTM2000Quad/WMTSCapabilities.xml?api=c01g732j2rsn6rk7p04gzm85167 (90-day key)

Let me know if we can provide you more details.

Thanks,
Grant

**Comment by dwsilk** [comment]
Hi Grant - thanks for letting us know, looks like this broke on Basemaps release last Thursday.

I get this error when selecting 'Add Layer' in QGIS 3.26.1
```TypeError: QgsCoordinateReferenceSystem(): arguments did not match any overloaded call:   overload 1: too many arguments   overload 2: too many arguments   overload 3: argument 1 has unexpected type 'NoneType'   overload 4: argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "/home/dsilk/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 786, in import_dataset
    self.set_project_srid()
  File "/home/dsilk/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 763, in set_project_srid
    crs = QgsCoordinateReferenceSystem(
TypeError: QgsCoordinateReferenceSystem(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: too many arguments
  overload 3: argument 1 has unexpected type 'NoneType'
  overload 4: argument 1 has unexpected type 'NoneType'
```

As you say I suspect it has something to do with the TileMatrixSet - we've updated it on the Basemaps side of things and I think the plugin is hardcoding the old TileMatrixSet and/or extracting the EPSG identifier from the old TileMatrixSet name.

**Comment by billgeo** [comment]
Hi @grantpearse new version has been released to the public QGIS Plugin repository. I think it takes a couple of days for it be 'approved' but you should be able to install it after that.

https://plugins.qgis.org/plugins/linz-data-importer/version/2.3.1/

**Comment by grantpearse** [comment]
Hi @billgeo - confirming that an upgrade to 2.3.1 of the plugin got the aerial basemap working again.  Thanks!
