### ISSUE TITLE
user testing

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#26]
Prior to release user testing will need to occur. 
- [ ] I will initially test with a windows machine (as this has had little attention)
- [ ] Send out to users for testing
- [ ] Document tests for users to conduct and confirm they had no issues

**Comment by SPlanzer** [comment]
- [ ] Understand the impact of the slowness of the first initial document getting when the plugin is loaded for the first time. This will be undertaking by asking users of there experience

further development will be required if a user gives up and kills the QGIS application rather than wait. If they just wait they will not experience the problem again.

**Comment by jducnuigeen** [comment]
When using the plugin the first time, and adding my key in, when I press Save QGIS appears to stall. Maybe a message to tell the user to be patient since it's working in the background.  After the first time, the plugin worked fine.
