### ISSUE TITLE
Improve CRS handling 

### ISSUE THREAD

**Issue by palmerj** [linz/linz-data-importer#4]
Currently WGS 84 Web Mercator (EPSG:3857) is used by default as all LDS WMTS services are served in this projection and it is not always a good idea to reproject WMTS.

To improve on this I suggest:

* WMS should be added using the QGIS project projection if supported. If the project projections is not supported then default it to WGS84. Providing a combo dropdown box option on the row for user selection is also another good idea
* For WMTS provide all tilematrix grid options in the UI using a combo dropdown box option on the row
* WFS I think you are limited to the datasource CRS only.

**Comment by SPlanzer** [comment]
At this stage this will be released in v2.0.0 (QGIS3). However, the feedback from #26 has the ability to change this current view of priority

**Comment by SPlanzer** [comment]
This is going to be implemented following the below logic:

* If no layers are already imported into the QGIS project: 
  * Import the layer in (one* of) its native crs
  * Notify the user the CRS has been changed
* elif the layer that is being imported native crs matches the project crs:
  * import silently 
* else if the layer's crs does not match the project crs:
  * import and have qgis reporject
  * Notify the user that things may get funky 

\* Adding a combo box against each spatial layer to select native crs options is to be explored.

**Comment by SPlanzer** [comment]
Done - but not quite as above. 

The user can now select from the servers CRS options for the dataset.
