### ISSUE TITLE
if dataset is not cached, warn user. 

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#40]
This really only relates to services with WMS (currently only LDS). 

When the domain details are saved for the first time and the plugin awaits get capability doc responses the plugin appears to freeze (as wms takes a long time to respond) 

The currently solution has a label warning this may take some time. This has low visibility. When hitting save a pop up dialog should be shown and warn the user.

**Comment by SPlanzer** [comment]
Stalebot Config update to exclude "enhancement"

**Comment by dwsilk** [comment]
Is WMS the main cause of the long cache time? We can probably just remove WMS support from the plugin at this point?

**Comment by SPlanzer** [comment]
> Is WMS the main cause of the long cache time? We can probably just remove WMS support from the plugin at this point?

That is correct

**Comment by SPlanzer** [comment]
WMS no longer supported by koordinates
