### ISSUE TITLE
Issues with addressing team work flow

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#43]
I have heard the LINZ addressing team have has issues with the LINZ-Data-Importer with their work flow. 

I have no other information so at this stage I will just visit them to understand what the issue is.

**Comment by SPlanzer** [comment]
I have met with them. They are no longer concerned but this is worth catching. 

When importing data of certain srs (they are not sure which) the plugin changes the projection to the incoming datasets srs (it always does this when importing the first data set via the importer for the session). At times when doing this they could not then see their current data that was in 4167. To get around this they are changing the OTF projection back to 4167 and then they can see all their data (including that imported via the importer plugin).

**Going forward**
* When this plugin sees its next round of dev (probably QGIS3 focused) this needs to be replicated to understand why they can not see the layers initially imported to the project prior to importing via the importer plugin. 
* Perhaps rather than the plugin turning OTF on and setting the projection for the first layer imported via the importer plugin, the plugin should only do this if no layers are in the project whether imported via the plugin or any other means . 

This is on hold awaiting the next round of dev

**Comment by palmerj** [comment]
> Perhaps rather than the plugin turning OTF on and setting the projection for the first layer imported via the importer plugin, the plugin should only do this if no layers are in the project whether imported via the plugin or any other means .

I would go with this option. I warning notification can be raised (if not already implemented) in when layers are added that do not match the project CRS
