### ISSUE TITLE
Error importing WFS data with qgis versions 2.18.20+

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#44]

**Comment by SPlanzer** [comment]
This seems to just affect the latest versions of QGIS 2. 

a user provided the below. 

```
2018-12-13T10:36:18    1    GetCapabilities failed for url https://data.linz.govt.nz/services;key=<KEY>/wfs?SERVICE=wfs&VERSION=2.0.0&REQUEST=GetFeature&TYPENAME=data.linz.govt.nz:layer-50221: unexpected end of file
```

**Comment by SPlanzer** [comment]
**Python console tests**

**QGIS 2.18.17**

```
uri = 'https://data.linz.govt.nz/services;key=<API_KRY>/wfs?SERVICE=wfs&VERSION=2.0.0&REQUEST=GetFeature&TYPENAME=data.linz.govt.nz:layer-50221'

layer=QgsVectorLayer(uri, 'test', 'WFS')
layer.isValid()
True
```


**QGIS 2.18.26**

```
uri = 'https://data.linz.govt.nz/services;key=<API_KEY>/wfs?SERVICE=wfs&VERSION=2.0.0&REQUEST=GetFeature&TYPENAME=data.linz.govt.nz:layer-50221'

layer=QgsVectorLayer(uri, 'test', 'WFS')
layer.isValid()
QGIS HANGINGS!!!
```

:confused:

**Comment by SPlanzer** [comment]
Potentially an issue with the change >>> https://github.com/qgis/QGIS/compare/final-2_18_20..final-2_18_21#diff-7f83d21b1d3b1afc39d33a7c9560cb59R439

https://github.com/qgis/QGIS/blob/9fba24a3f2af623da215ee5f9ee933bb4ec5b463/src/providers/wfs/qgswfsfeatureiterator.cpp#L439-L487

**Comment by palmerj** [comment]
I'd raise a bug on issues.qgis.org with test case and then raise a QGIS-Developer mail message as well

**Comment by SPlanzer** [comment]
Thanks for chiming in.

Thats the plan, I will do that right now. I did really want to test it with other WFS2 services that are not koordinates implemented. I have not found the ideal services to do this. Any recommendations? 

Most I have come across do not implement `typeNames` as per the spec. i,e they still use typeName`

For example:
should be WFS2 `http://giswebservices.massgis.state.ma.us/geoserver/wfs?request=getcapabilities`

But they use 'typename'
`http://giswebservices.massgis.state.ma.us/geoserver/wfs?service=WFS&version=2.0.0&request=GetFeature&typename=massgis:GISDATA.PATHWAYS_ARC_M219`

**Comment by SPlanzer** [comment]
issue opened against qgis project https://issues.qgis.org/issues/20808

**Comment by SPlanzer** [comment]
still an issue

**Comment by SPlanzer** [comment]
QGIS devs do not plan to fix this. see - https://issues.qgis.org/issues/20808

**Comment by palmerj** [comment]
Pushes us closer to having to make the jump with 2.18 now EOL
