### ISSUE TITLE
Bug: can't find 'NZ Aerial Imagery' layer

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#56]
Trying to find 'NZ Aerial Imagery' layer returns no results

![Missing nz aerial imagery](https://user-images.githubusercontent.com/8991188/73707132-7d6d4600-475f-11ea-9f58-76c8bc24276a.PNG)

**Comment by billgeo** [comment]
See here https://data.linz.govt.nz/set/4702-nz-aerial-imagery/

**Comment by SPlanzer** [comment]
Cheers @billgeo for reviewing this. 

This is a set and not described in the [WMTSCapabilities document](https://data.linz.govt.nz/services;key=5369352ac2464a0ba503d403ff50b3c3/wmts/1.0.0/WMTSCapabilities.xml)
it appears these are described in another [set/WMTS WMTSCapabilities document](https://data.linz.govt.nz/services;key=5369352ac2464a0ba503d403ff50b3c3/wmts/1.0.0/set/4702/WMTSCapabilities.xml)

Some work will need to be undertake to understand if there are any barriers to including sets (e.g are the docs OGC complaint to ensure easy integration with AGIS API?) to the plugin

**Comment by billgeo** [comment]
They should be OGC compliant and you can definitely add them to QGIS with the default WMTS importer.
