### ISSUE TITLE
Enhancement: Make menu title more human readable

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#57]
In the menu. the tool is call `linz-data-importer`. Looks like convention in QGIS is to have Title Case menu items, i.e. `LINZ Data Importer`
![image](https://user-images.githubusercontent.com/8991188/73707272-fa002480-475f-11ea-8e53-bed5048a91a2.png)

**Comment by SPlanzer** [comment]
Good call, Effort is minimal to change this
