### ISSUE TITLE
Add LINZ's new Aerial Imagery Basemaps Services

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#62]
As a QGIS user, I'd like to search, find and add LINZ's new Aerial Imagery Basemap services (and any future basemap services they add) to my map in QGIS.

https://basemaps.linz.govt.nz

**Comment by strk** [comment]
I need an API key for testing work on this.
Waiting for a reply from the appropriate email address to get one

**Comment by strk** [comment]
Got the API key. WIth the key I can successfully add basemaps to QGIS without using any plugin but simply pointing QGIS at the capabilities document, using this URL:

> https://basemaps.linz.govt.nz/v1/tiles/aerial/WMTSCapabilities.xml?api=xxxxx

QGIS is then able to find out how to access each tile from each published layer.

This plugin, instead, makes some assumptions about where the capabilities document should be found, hard-coding a `/services;key` suffix to the baseurl.

@SPlanzer do you have any idea where this assumption comes from ? Is it an older or newer OWS standard ?

**Comment by strk** [comment]
The response from the basemap service ("The specified key does not exist") suggests me it is trying to fetch some data from AWS S3...

**Comment by SPlanzer** [comment]
> This plugin, instead, makes some assumptions about where the capabilities document should be found, hard-coding a /services;key suffix to the baseurl.
>
> @SPlanzer do you have any idea where this assumption comes from ? Is it an older or newer OWS standard ?

This is hardcoded in the plugin source code 

https://github.com/linz/linz-data-importer/blob/e82b7c30019a45e9e0a5ab16a8d070cc0913bc95/linz-data-importer/linz_data_importer.py#L756-L769

**Comment by strk** [comment]
Not only the capabilities XML is hardcoded, but also the tiles access URL (rather than read from the capabilities XML)

**Comment by strk** [comment]
Well, in #66 I went on with hard-coding to at least support basemaps.linz.govt.nz
