### ISSUE TITLE
Provide progress bar when importing WxS GetCapabilities document

### ISSUE THREAD

**Issue by palmerj** [linz/linz-data-importer#7]
At the moment the QGIS UI locked up for over 2 minutes when the API key is saved or the plugin UI is started for the first time in a new QGIS session. This is because loading the LDS WxS capability documents is slow

It would be good to add some type of non-blocking progress bar when loading the WxS capability documents.

**Comment by palmerj** [comment]
My last import took 5mins!

**Comment by SPlanzer** [comment]
> My last import took 5mins!
Wow. Yeah that is not going to work.

**Comment by SPlanzer** [comment]
#9 has made the loading of documents much faster. The only time the loading is slow is the first time the plugin is ever ran. I am hoping the users can tolerate one slow load and then the plugin handles all future document getting in the background. 

Feedback will be gathered via #26

**Comment by SPlanzer** [comment]
The first time a service is added in the settings the plugin can become un-responsive. There is a label indicating this. There after due to caching there are no un-responsive issues.

I do not see this as required
