### ISSUE TITLE
LINZ Basemaps without an API key

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#70]
Thanks to Sandro linz basemaps can be added to QGIS via the plugin importer. 

Following the plugins design this does require an API key. The basemaps however do not require a key (but some users do use one) and uptake may be higher if we allow users to import the basemaps without requesting and API key. 

One solution is just to have LINZ base maps as a default dataset that is always available in the plugin.

**Comment by billgeo** [comment]
This is actually incorrect. I think all users need a key. But it's not super obvious from the documentation. The 'standard user' key is pregenerated in the URL on https://basemaps.linz.govt.nz. Basemaps team can confirm.

**Comment by billgeo** [comment]
Closing this as there's nothing to do here.
