### ISSUE TITLE
Basemaps - API key options

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#76]
As we are adding basemaps I would like to capture some options and discussion for managing API keys.

The basemaps have been implemented as all other layers - that is, the user adds their key via the settings tab. The plugin docs have been updated to point them at https://basemaps.linz.govt.nz for info on API keys. 

### Key options 
* Copy the API key from https://basemaps.linz.govt.nz
  * This is only valid for so many days and must be rotated
  * If using this our docs need to include this information else we will have some very confused users when the key expires
* Get a developer key allocated for the plugin
  * Depending how this is implemented it could expose the key to the public
  * It would allow us to track the use of the plugin 

### Also 
https://basemaps.linz.govt.nz is confusing in terms of pulling the API key out of the API url. 
* First you have to know to click on the hamburger menu. 
* Then you click on "the Get an API key" button. Nothing in respect to an API appears to change??? (it is embedded in a URL of which the UI only allows you to the the start of and no API key until you copy it and view it elsewhere)
* There is also no doc saying this will be rotated out

**Comment by billgeo** [comment]
The Basemaps Product Owner has indicated a preference for all QGIS users to use their own API key. So option 1 in your description above. Although the QGIS users are also able to request a 'developer API key' if they want.

**Comment by billgeo** [comment]
> There is also no doc saying this will be rotated out

There is a Basemaps fix for this going in later today.

> First you have to know to click on the hamburger menu.
> Then you click on "the Get an API key" button. Nothing in respect to an API appears to change??? (it is embedded in a URL of which the UI only allows you to the the start of and no API key until you copy it and view it elsewhere)

I would suggest raising a request to improve this on https://github.com/linz/basemaps rather than implement a workaround.
