### ISSUE TITLE
Base maps UX visibility 

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#77]
Base maps in the current UI have little visibility.

These are added as any other WMTS service. 

if the another data services WMTS datasets are already added, base maps is buried amongst all these. 

Would we like to see basemaps have more visibility in the plugin? Its own menu item, tab or button?

**Comment by billgeo** [comment]
Agree with this. I think we could improve the usability of find the services people want.

**Comment by billgeo** [comment]
Thought about adding a button for basemaps. But that's a bit confusing as it is essentially just another WMTS service. For now have implemented domain filtering in #88. And will revisit this later if needed. I think a dropdown to filter by domain could be the way to do this.
