### ISSUE TITLE
Transfer ownership of the plugin in the offical QGIS plugin repo to a LINZ account

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#78]
The original plugin was uploaded to the QGIS plugin repo via my (@SPlanzer ) osgeo account. 

This means I am the only one able to post updates. We need to migrate to using an account accessible by all DS members.

**Comment by SPlanzer** [comment]
It seems I can transfer ownership of the plugin to another accoubt(see- http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-QGIS-Plugins-transfer-question-td5359883.html)

I will therefore create an account for linzdataserviceadmin@linz.govt.nz and transfer ownership of the plugin to this.

**Comment by SPlanzer** [comment]
I am having issues creating an account for linzdataserviceadmin@linz.govt.nz as I am required to send an email from this inbox but am not authorised to do so.

To create an osgeo account for linzdataserviceadmin@linz.govt.nz I must must send an email to `mantra-request@osgeo.org` from linzdataserviceadmin@linz.govt.nz. See instructions over at osgeo for account creation https://id.osgeo.org/ldap/create. I however do not have permission to send emails from the  linzdataserviceadmin@linz.govt.nz account.  

I could possibly use my own email and ask for the account to be created for linzdataserviceadmin@linz.govt.nz but the entire reason for this process is to establish trust with the email address owner and I would hope this approach would not work. 

@billgeo @imincik do you have permission to email from this account? Else I will ask service desk for this privilege so that I can create a osgeo account for linzdataserviceadmin@linz.govt.nz

**Comment by billgeo** [comment]
As discussed. Probably best to just transfer the plugin to your replacement when they start. Let's put this back on the blocked lane for now.

**Comment by strk** [comment]
Simon: I can give you the mantra, just ping me in Slack..

**Comment by SPlanzer** [comment]
I created an account for linzdataserviceadmin@linz.govt.nz and received the messgae
>Check your email for a link to confirm your account. If it doesn't appear within a few minutes, check your spam folder. 

However and email was never received - Will follow up however a little problematic as I can not send emails from linzdataserviceadmin@linz.govt.nz

**Comment by SPlanzer** [comment]
oh and just seen this comment - https://github.com/linz/ds-group-epics/issues/145#issuecomment-717079150

**Comment by billgeo** [comment]
> check your spam folder.

Found it in here. :)

**Comment by billgeo** [comment]
I clicked the link but it needed the the password. @SPlanzer can you share the pwd with myself @imincik and @strk ? Also looks like the link is now invalid. So might have to restart the process.

**Comment by strk** [comment]
When the link is visited it becomes invalid, and sends a password (again check in the spam folder)

**Comment by SPlanzer** [comment]
> I clicked the link but it needed the the password. @SPlanzer can you share the pwd with myself @imincik and @strk ? Also looks like the link is now invalid. So might have to restart the process.

sorry just seen this. Password is in lastpass will share now
