### ISSUE TITLE
Deploy LINZ Data Importer plugin to OSGEO plugin repo

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#83]
@billgeo commented on [Mon Nov 02 2020](https://github.com/linz/ds-infra-team/issues/713)

So users outside of LINZ have access to it.

Depends on https://github.com/linz/linz-data-importer/issues/78

**Comment by SPlanzer** [comment]
Done - 2.1.0 released to official plugin repo

**Comment by billgeo** [comment]
Great stuff! Thanks @SPlanzer and @strk for your work on this.
