### ISSUE TITLE
WFS: Add option to fetch data for the given map canvas extent

### ISSUE THREAD

**Issue by palmerj** [linz/linz-data-importer#89]
This will allow large datasets like parcels to be added to a project. At the moment the WFS connection string will force the whole dataset to be cached first before it can be used correction in the project. In the case of NZ Parcels that's over 5GB of data. Adding these options will allow the user to request data within the viewable map window.

You can achieve this by adding the WFS provider options `restrictToRequestBBOX=1 and pagingEnabled='true'`

Not sure if this should be the main method or a user option. In some cases the user might want to see all the data in the layer table (vs just the current extent), so it's probabily best to provide an option for this.

**Comment by billgeo** [comment]
`restrictToRequestBBOX=1` doesn't work but `bbox=1` does. 
See stale issue here https://github.com/qgis/QGIS/issues/40826

**Comment by palmerj** [comment]
I just tested now with QGIS 3.16.3 and providing provider URI parameters work:

```
pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:4167' typename='data.linz.govt.nz:layer-50772' url='https://data.linz.govt.nz/services;key=xxxx/wfs/layer-50772' version='auto' works :)
```
