### ISSUE TITLE
Test on older versions of QGIS 3

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#96]
The plugin is designed for public use, with users using different versions of QGIS 3. It is possible that there could be a breaking change between minor versions, so it would be good to test in the CI pipeline (and locally?) against multiple versions of QGIS 3. No need to test on older versions < 3.

**Comment by l0b0** [comment]
We should test against the long-term releases (LTRs), as shown in the [release schedule](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).
